export const routes = {
    home: '/',
    login: '/login',
    signup: '/signup',
    cart: '/cart',
    userAccount: '/user-account',
    checkOut: '/check-out',
    myOrders: '/my/orders',
    adminOrders: '/admin/orders',
    products: '/products',
    adminProducts: '/admin/products',
    adminProductDetails: '/admin/products/product-details/:id',
    adminProductNew: '/admin/products/product-details/new',
    orderDetails: 'order-details/:id',
    adminOrderDetails: '/admin/orders/order-details/:id',
    myOrderDetails: '/my/orders/order-details/:id',
};
